---

- name: Stopping Web Services
  become: "yes"
  gather_facts: "no"
  hosts:
    - web
  tasks:
    - name: Stopping mariadb
      service:
        name: mariadb
        state: stopped
      tags:
        - stop_database

- name: Starting Web Services
  become: "yes"
  gather_facts: "no"
  hosts:
    - web
  tasks:
    - name: Start mariadb
      service:
        name: mariadb
        state: started
      tags:
        - start_database
