---
- name: "Checking Linux Configuration"
  hosts: linux
  vars_files:
    - vars/vault
  roles:
    - common
    - linux
  tags:
    - configuration


- name: "Checking Database Configuration"
  hosts: db
  vars_files:
    - vars/vault
  roles:
    - databases
  tags:
    - configuration

- name: "Checking Webserver Configuration"
  hosts: web
  vars_files:
    - vars/vault
  roles:
    - webservers
  tags:
    - configuration

- name: "Checking Windows Configuration"
  hosts: windows
  vars_files:
    - vars/vault
    - vars/winrm.yml
  roles:
    - common
    - windows
  tags:
    - configuration
