---
- name: "Webserver Tasks"
  hosts: linux_webservers
  become: yes
  tags:
    - webservers
  tasks:
  roles:
    - webservers

# Enable this when we have an app to install
#- name: "Installing appserver"
#  hosts: app
#  become: yes
#  tags:
#    - start_appserver
#  tasks:
#    - include_playbook: appserver.yml
#      tags:
#        - install

- name: "Database tasks"
  hosts: linux_databases
  become: yes
  tags:
    - database
  tasks:
  roles:
    - databases

- name: Microsoft Windows patching
  hosts: windows
  import_playbook: windows_patching.yml
  tags:
    - patches

- name: RHEL based patching
  hosts: linux
  import_playbook: rhel-like_patching.yml
  tags:
    - patches
