---
- name: Ensure WEBSERVER is in roles.txt
  lineinfile:
    path: /etc/ansible/roles.txt
    line: 'Webserver is configured to be running'
    create: yes
  tags:
    - running

- name: Ensure apache is installed
  yum:
    name: httpd
    state: installed
  tags:
    - running
- name: Stopping apache
  service:
    name: httpd
    state: stopped
  tags:
    - stopped
- name: Ensure apache is running
  service:
    name: httpd
    state: started
  tags:
    - running
