---
- name: Ensure DATABASE is in MOTD
  lineinfile:
    path: /etc/ansible/roles.txt
    create: yes
    line: 'Database is configured to run'
  tags:
    - running

- name: Ensuring mariadb is installed
  yum:
    name: mariadb-server
    state: installed
  tags:
    - running

- name: Stopping mariadb (if needed)
  service:
    name: mariadb
    state: stopped
  tags:
    - stopped

- name: Ensure mariadb is running
  service:
    name: mariadb
    state: started
  tags:
    - running
